# Generated by Django 5.2.8 on 2025-12-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0002_alter_categoria_options_categoria_categoria_padre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='app_finanzas.categoria'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nombre',
            field=models.CharField(default='Presupuesto Mensual', max_length=50),
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='categoria',
        ),
    ]
