# Generated by Django 5.2.8 on 2025-12-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0004_whatsapplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='nivel_alerta_enviado',
            field=models.IntegerField(default=0),
        ),
    ]
