# Generated by Django 5.2.8 on 2025-12-09 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0005_presupuesto_nivel_alerta_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_MONTO', 'Esperando Monto'), ('ESPERANDO_CATEGORIA', 'Esperando Categoria')], default='INICIO', max_length=50)),
                ('datos_temporales', models.JSONField(default=dict)),
                ('ultimo_mensaje', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
