# Generated by Django 5.2.8 on 2025-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0006_whatsappsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='estado',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ESPERANDO_MONTO', 'Esperando Monto'), ('ESPERANDO_CATEGORIA_PADRE', 'Esperando Categoria Padre'), ('ESPERANDO_CATEGORIA_HIJA', 'Esperando Categoria Hija')], default='INICIO', max_length=50),
        ),
    ]
