# Generated by Django 5.2.8 on 2025-12-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
